### PR TITLE
Delete obsolete files

### PR DESCRIPTION
**Pull request by Thymir**
Deleted many legacy files
Deleted build scripts and makefiles
Deleted package manager files
Renamed projects so agnostic of msvc version

### CODE REVIEW

**Comment by franpuerta** [comment]
Is [library_MSVC14.vcxproj.filters](https://github.com/systelab/loki/blob/DeleteObsoleteFiles/src/library_MSVC14.vcxproj.filters) needed?

**Comment by franpuerta** [comment]
I suggest removing lib folder as well as it only has a README file (and usually lib folders are meant for generated binaries, which should never been uploaded here).

**Comment by franpuerta** [comment]
https://github.com/systelab/loki/blob/DeleteObsoleteFiles/include/Makefile can be removed, right?

**Comment by franpuerta** [comment]
Can we remove https://github.com/systelab/loki/tree/DeleteObsoleteFiles/macosx?

**Comment by Thymir** [comment]
> Is [library_MSVC14.vcxproj.filters](https://github.com/systelab/loki/blob/DeleteObsoleteFiles/src/library_MSVC14.vcxproj.filters) needed?

Removed this as well as all the others *vcxproj.filters

**Comment by Thymir** [comment]
> I suggest removing lib folder as well as it only has a README file (and usually lib folders are meant for generated binaries, which should never been uploaded here).

Done

> Can we remove https://github.com/systelab/loki/tree/DeleteObsoleteFiles/macosx?

Initially I though we might want to preserve some support for macos in the future. I agree it can be deleted now

> https://github.com/systelab/loki/blob/DeleteObsoleteFiles/include/Makefile can be removed, right?

Indeed, good catch

**Review by franpuerta — APPROVED** [review]

**Pull request merged**
